### ISSUE TITLE
Number of Group Members:

### ISSUE THREAD

**Issue by Alusp** [Alusp/meals-capstone-project#21]
Hi :wave: 

**In this group project we are two members:** @skyv26  and @Alusp.

Because we are 2 members that's why we removed the `cards` and `issues` for **Student C**

[Click here to see our GitHub project ](https://github.com/Alusp/meals-capstone-project/projects/1)

**Comment by muneebulrehman** [comment]
Hi team, 

Good job so far! I see you put a lot of effort into this project. However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [x] Since you are a group of 2 people, all the cards/work for student c should be removed from the Kanban board.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by skyv26** [comment]
@muneebulrehman Thank you for addressing the issue. We removed the cards for Student C.

**Comment by leonardodiasb** [comment]
# Status: ✔️ Project Approved ✔️ 

Hello @Alusp 🔥 

You did all the instructions that the previous Code Reviewers gave you👍🏽 

Now you can start this project. 🚀 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

 - [OPTIONAL] You could assign someone from the group for the 'group task' cards as it is written in the project requirement.
 
<img width="978" alt="image" src="https://user-images.githubusercontent.com/61919617/187225790-c30a74d2-8994-42d7-893d-b7af094e5156.png">


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Alusp** [comment]
Thank you for the review @leonardodiasb
